package demo.services;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(code = HttpStatus.BAD_REQUEST)
public class BadInputException extends RuntimeException {
	// this value was generated by clicking the compilation warning next to the
	// class name,
	// and choosing "Add generated serial version ID"
	// Note: Exceptions and their derived classes are Serializable,
	// hence, they should declare the following serialVersionUID,
	// to avoid object serialization issues, when recompiled
	private static final long serialVersionUID = -724809990103580059L;

	public BadInputException() {
	}

	public BadInputException(String message) {
		super(message);
	}

	public BadInputException(Throwable cause) {
		super(cause);
	}

	public BadInputException(String message, Throwable cause) {
		super(message, cause);
	}

}
